name: "PHPStan"
description: "check for configuration file, install and execute PHPStan"

runs:
  using: composite
  steps:
    - name: Install PHPStan
      shell: bash
      if: ${{ hashFiles('phpstan.neon', 'phpstan.neon.dist') != '' }}
      working-directory: shop
      run: |
        composer require --dev \
          "phpstan/phpstan:^1" \
          --no-interaction \
          --no-progress

    - name: Run PHPStan
      shell: bash
      if: ${{ hashFiles('phpstan.neon', 'phpstan.neon.dist') != '' }}
      working-directory: shop
      run: |
        if [[ -f vendor/${{ inputs.composer_package_name }}/phpstan.neon ]]; then
          CONFIG="vendor/${{ inputs.composer_package_name }}/phpstan.neon"
        elif [[ -f vendor/${{ inputs.composer_package_name }}/phpstan.neon.dist ]]; then
          CONFIG="vendor/${{ inputs.composer_package_name }}/phpstan.neon.dist"
        else
          echo "No PHPStan config found, skipping."
          exit 0
        fi

        vendor/bin/phpstan analyse \
          --configuration="$CONFIG" \
          --no-progress \
          --quiet