name: "Clear TMP to invalidate caches"
description: ""

runs:
  using: composite
  steps:
    - name: Clear TMP folder
      shell: bash
      working-directory: shop
      run: |
        rm -rf ./source/tmp/*