name: "PHP linting"
description: "Checks for PHP systax errors"

runs:
  using: composite
  steps:
    - name: PHP syntax check
      shell: bash
      run: |
        if [[ -z "${{ inputs.syntax_check_paths }}" ]]; then
          echo "No syntax check paths provided - skipping PHP syntax check."
          exit 0
        fi

        IFS=',' read -ra PATHS <<< "${{ inputs.syntax_check_paths }}"

        for RAW_PATH in "${PATHS[@]}"; do
          PATH_TRIMMED="$(echo "$RAW_PATH" | xargs)"

          if [[ -z "$PATH_TRIMMED" ]]; then
            continue
          fi

          if [[ -d "$PATH_TRIMMED" ]]; then
            echo "Syntax check in $PATH_TRIMMED"
            find "$PATH_TRIMMED" -name "*.php" -print0 | xargs -0 -n1 php -l
          else
            echo "Path '$PATH_TRIMMED' does not exist - skipped."
          fi
        done